module.exports = function messages(users) {
  return [
    {
      name: "Aaron",
      email: "Aaron@email.com",
      password: "chat",
      joined: new Date(),
      id: "aar123",
      message: "Hi",
    },
    {
      name: "Aradhenu",
      email: "Ardenu@email.co",
      password: "chat",
      joined: new Date(),
      id: "ard123",
      message: "Ki holo",
    },
    {
      name: "Abdul",
      email: "Abdul.co",
      password: "chat",
      joined: new Date(),
      id: "abd123",
      message: "Salam-alaikum",
    },
    {
      name: "ArmanKaur",
      email: "Arman.co",
      password: "chat",
      joined: new Date(),
      id: "arm123",
      message: "Satsarikalji",
    },
    {
      name: "Arihanth",
      email: "Arihanth.co",
      password: "chatting",
      joined: new Date(),
      id: "ari123",
      message: "Namaste",
    },
    {
      name: "Aan-Su-Ki",
      email: "Aansuki.co",
      password: "notchat",
      joined: new Date(),
      id: "aan123",
      message: "Moshi-Moshi",
    },
    {
      name: "Ari",
      email: "Ari.co",
      password: "chat",
      joined: new Date(),
      id: "ari123",
      message: "Shalom",
    },
    {
      name: "Arigato",
      email: "Arigato.co",
      password: "nochat",
      joined: new Date(),
      id: "ari-123",
      message: "Moshi-Moshi",
    },
    {
      name: "test",
      email: "email@email.com",
      password: "123",
      joined: new Date(),
      id: "test123",
      message: "testing",
    },
  ];
};
